// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreatePath(arg1:string):Promise<void>;

export function GetPathsStatus():Promise<Array<domain.PathStatus>>;

export function Greet(arg1:string):Promise<string>;
