// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AppendEnv(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function CreatePath(arg1:string):Promise<void>;

export function GenerateShortcut(arg1:string):Promise<void>;

export function GetCurrentConfigPath():Promise<string>;

export function GetEnvStatus():Promise<Array<dto.EnvStatus>>;

export function GetPathsStatus():Promise<Array<dto.PathStatus>>;

export function GetShortcuts():Promise<Array<dto.ShortcutStatus>>;

export function GetSoftwareStatus():Promise<Array<dto.SoftwareStatus>>;

export function Greet(arg1:string):Promise<string>;

export function SelectAndLoadConfig():Promise<string>;

export function SetEnv(arg1:string,arg2:string,arg3:string):Promise<void>;
