// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendEnv(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendEnv'](arg1, arg2, arg3);
}

export function CreatePath(arg1) {
  return window['go']['main']['App']['CreatePath'](arg1);
}

export function GetCurrentConfigPath() {
  return window['go']['main']['App']['GetCurrentConfigPath']();
}

export function GetEnvStatus() {
  return window['go']['main']['App']['GetEnvStatus']();
}

export function GetPathsStatus() {
  return window['go']['main']['App']['GetPathsStatus']();
}

export function GetSoftwareStatus() {
  return window['go']['main']['App']['GetSoftwareStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectAndLoadConfig() {
  return window['go']['main']['App']['SelectAndLoadConfig']();
}

export function SetEnv(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnv'](arg1, arg2, arg3);
}
