// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AppendEnv(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function CreatePath(arg1:string):Promise<void>;

export function GetEnvStatus():Promise<Array<domain.EnvStatus>>;

export function GetPathsStatus():Promise<Array<domain.PathStatus>>;

export function Greet(arg1:string):Promise<string>;

export function SetEnv(arg1:string,arg2:string,arg3:string):Promise<void>;
