// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePath(arg1) {
  return window['go']['main']['App']['CreatePath'](arg1);
}

export function GetPathsStatus() {
  return window['go']['main']['App']['GetPathsStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
